language: node_js
node_js:
  - "16.10.0"
dist: bionic
sudo: required
branches:
  only:
  - master
before_script:
  - npm install -g yarn && yarn
  - npm install -g @angular/cli
script:
# - ng lint
- ng build --prod
